# Generated by Django 2.0.7 on 2018-07-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180720_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='tag',
            field=models.CharField(default='xs', max_length=255, null=True),
        ),
    ]
