# Generated by Django 2.0.7 on 2018-07-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_img_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
