# Generated by Django 2.0.7 on 2018-07-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_img_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='followers',
            field=models.SmallIntegerField(default=0),
        ),
    ]
