# Generated by Django 2.0.7 on 2018-07-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_te'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='followers',
            field=models.UUIDField(null=True),
        ),
    ]
