# Generated by Django 2.0.7 on 2018-07-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180720_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Te',
        ),
    ]
