# Generated by Django 2.0.7 on 2018-07-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guanzhu_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='作者')),
                ('uuid', models.UUIDField(null=True, verbose_name='uuid')),
                ('parent_id', models.SmallIntegerField(verbose_name='类型ID')),
            ],
        ),
        migrations.CreateModel(
            name='Spider_guanzhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.SmallIntegerField(verbose_name='上级ID')),
                ('group_id', models.IntegerField(verbose_name='作者ID')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('author_avatar', models.CharField(max_length=255, null=True, verbose_name='头像')),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('img_urls', models.TextField(null=True, verbose_name='图片')),
                ('media_url', models.CharField(max_length=255, null=True, verbose_name='视频')),
                ('from_url', models.CharField(max_length=255, null=True, verbose_name='内容页链接')),
                ('forward', models.TextField(null=True, verbose_name='转发内容')),
                ('published_at', models.DateTimeField(null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='入库时间')),
            ],
        ),
        migrations.CreateModel(
            name='Spider_kuaixun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.SmallIntegerField(verbose_name='内容分类标识')),
                ('origin_url', models.CharField(max_length=255, null=True, verbose_name='内容页链接')),
                ('origin_from', models.CharField(max_length=255, null=True, verbose_name='数据来源网站')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='标题')),
                ('thumb', models.CharField(max_length=255, null=True, verbose_name='缩略图')),
                ('description', models.TextField(null=True, verbose_name='内容概述')),
                ('content', models.TextField(null=True, verbose_name='正文')),
                ('created_at', models.DateTimeField(null=True, verbose_name='发表时间')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='入库时间')),
                ('is_red', models.SmallIntegerField(default=0, null=True, verbose_name='内容标红')),
                ('is_more', models.SmallIntegerField(default=0, null=True, verbose_name='查看详情')),
                ('to_url', models.CharField(max_length=255, null=True, verbose_name='查看详情链接')),
            ],
        ),
        migrations.CreateModel(
            name='Spider_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.SmallIntegerField(verbose_name='内容分类标识')),
                ('origin_url', models.CharField(max_length=255, null=True, verbose_name='内容页链接')),
                ('origin_from', models.CharField(max_length=255, null=True, verbose_name='数据来源网站')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='标题')),
                ('thumb', models.CharField(max_length=255, null=True, verbose_name='缩略图')),
                ('description', models.TextField(null=True, verbose_name='内容概述')),
                ('content', models.TextField(null=True, verbose_name='正文')),
                ('created_at', models.DateTimeField(null=True, verbose_name='发表时间')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='入库时间')),
                ('author', models.CharField(max_length=255, null=True, verbose_name='作者')),
            ],
        ),
    ]
