# Generated by Django 2.0.7 on 2018-07-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider_guanzhu',
            name='media_url',
            field=models.TextField(null=True, verbose_name='视频'),
        ),
    ]
