# Generated by Django 2.0.7 on 2018-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uce', '0002_auto_20180724_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_fxh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('English_name', models.CharField(max_length=255, null=True)),
                ('chinese_name', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(max_length=255, null=True)),
                ('introduction', models.TextField(null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('circulation', models.CharField(max_length=255, null=True)),
                ('exchange', models.CharField(max_length=255, null=True)),
                ('published_at', models.DateField(null=True)),
                ('white_paper', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('block_station', models.CharField(max_length=255, null=True)),
                ('related_concepts', models.CharField(max_length=255, null=True)),
                ('is_token', models.SmallIntegerField(null=True)),
                ('token_platform', models.CharField(max_length=255, null=True)),
                ('crowdfunding_price', models.CharField(max_length=255, null=True)),
                ('origin_url', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
