# Generated by Django 2.0.7 on 2018-07-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uce', '0003_currency_fxh'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_fxh',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
