# Generated by Django 2.0.7 on 2018-07-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uce', '0004_currency_fxh_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_bsj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('English_name', models.CharField(max_length=255, null=True)),
                ('short_name', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(max_length=255, null=True)),
                ('introduction', models.TextField(null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('circulation', models.CharField(max_length=255, null=True)),
                ('published_at', models.DateField(null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('block_station', models.CharField(max_length=255, null=True)),
                ('origin_url', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('ico_cost', models.CharField(max_length=255, null=True)),
                ('ico_amount', models.CharField(max_length=255, null=True)),
                ('crowdfunding_way', models.CharField(max_length=255, null=True)),
                ('crowdfunding_amount', models.CharField(max_length=255, null=True)),
                ('opening_price', models.CharField(max_length=255, null=True)),
                ('successful_crowdfunding_q', models.CharField(max_length=255, null=True)),
                ('crowdfunding_goal', models.CharField(max_length=255, null=True)),
                ('successful_crowdfunding_a', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
