# Generated by Django 2.0.7 on 2018-07-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uce', '0005_currency_bsj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=255, null=True)),
                ('cn_name', models.CharField(max_length=255, null=True)),
                ('short_name', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(max_length=255, null=True)),
                ('introduction', models.TextField(null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('circulation', models.CharField(max_length=255, null=True)),
                ('exchange', models.CharField(max_length=255, null=True)),
                ('published_at', models.DateField(null=True)),
                ('white_paper', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('block_station', models.CharField(max_length=255, null=True)),
                ('related_concepts', models.CharField(max_length=255, null=True)),
                ('is_token', models.SmallIntegerField(null=True)),
                ('token_platform', models.CharField(max_length=255, null=True)),
                ('ico_cost', models.CharField(max_length=255, null=True)),
                ('origin_url', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
