# Generated by Django 2.0.7 on 2018-07-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uce', '0006_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
