# Generated by Django 2.0.7 on 2018-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uce', '0008_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
