# Generated by Django 2.0.7 on 2018-08-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uce', '0009_auto_20180804_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=255, null=True)),
                ('symbol', models.CharField(max_length=255, null=True)),
                ('period', models.CharField(max_length=255, null=True)),
                ('open', models.CharField(max_length=255, null=True)),
                ('close', models.CharField(max_length=255, null=True)),
                ('high', models.CharField(max_length=255, null=True)),
                ('low', models.CharField(max_length=255, null=True)),
                ('last', models.CharField(max_length=255, null=True)),
                ('change', models.CharField(max_length=255, null=True)),
                ('quoteVolume', models.CharField(max_length=255, null=True)),
                ('baseVolume', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
